//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FileTransfer.proto
namespace CmdlinkFileTransfer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDirectory")]
  public partial class GetDirectory : global::ProtoBuf.IExtensible
  {
    public GetDirectory() {}
    
    private string _DirectoryName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DirectoryName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DirectoryName
    {
      get { return _DirectoryName; }
      set { _DirectoryName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDirectoryResponse")]
  public partial class GetDirectoryResponse : global::ProtoBuf.IExtensible
  {
    public GetDirectoryResponse() {}
    
    private string _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<CmdlinkFileTransfer.GetDirectoryResponse.DirEntry> _direntry = new global::System.Collections.Generic.List<CmdlinkFileTransfer.GetDirectoryResponse.DirEntry>();
    [global::ProtoBuf.ProtoMember(2, Name=@"direntry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CmdlinkFileTransfer.GetDirectoryResponse.DirEntry> direntry
    {
      get { return _direntry; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DirEntry")]
  public partial class DirEntry : global::ProtoBuf.IExtensible
  {
    public DirEntry() {}
    
    private string _FileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FileName
    {
      get { return _FileName; }
      set { _FileName = value; }
    }
    private ulong _Size;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Size
    {
      get { return _Size; }
      set { _Size = value; }
    }
    private uint _CreationDate;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CreationDate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint CreationDate
    {
      get { return _CreationDate; }
      set { _CreationDate = value; }
    }
    private uint _LastWriteDate;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"LastWriteDate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint LastWriteDate
    {
      get { return _LastWriteDate; }
      set { _LastWriteDate = value; }
    }
    private uint _Permissions;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Permissions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Permissions
    {
      get { return _Permissions; }
      set { _Permissions = value; }
    }
    private CmdlinkFileTransfer.GetDirectoryResponse.DirEntry.FileType _filetype;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"filetype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CmdlinkFileTransfer.GetDirectoryResponse.DirEntry.FileType filetype
    {
      get { return _filetype; }
      set { _filetype = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FileType")]
    public enum FileType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FileTypeDir", Value=0)]
      FileTypeDir = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FileTypeFile", Value=1)]
      FileTypeFile = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FileTypeSymlink", Value=2)]
      FileTypeSymlink = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FileTypeOther", Value=3)]
      FileTypeOther = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetFile")]
  public partial class GetFile : global::ProtoBuf.IExtensible
  {
    public GetFile() {}
    
    private string _FileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FileName
    {
      get { return _FileName; }
      set { _FileName = value; }
    }

    private ulong _StartOffset = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"StartOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong StartOffset
    {
      get { return _StartOffset; }
      set { _StartOffset = value; }
    }

    private ulong _Count = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteFile")]
  public partial class DeleteFile : global::ProtoBuf.IExtensible
  {
    public DeleteFile() {}
    
    private string _FileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FileName
    {
      get { return _FileName; }
      set { _FileName = value; }
    }

    private bool _AllUnits = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AllUnits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool AllUnits
    {
      get { return _AllUnits; }
      set { _AllUnits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteFileResponse")]
  public partial class DeleteFileResponse : global::ProtoBuf.IExtensible
  {
    public DeleteFileResponse() {}
    
    private string _Status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAudioFile")]
  public partial class GetAudioFile : global::ProtoBuf.IExtensible
  {
    public GetAudioFile() {}
    
    private string _FileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FileName
    {
      get { return _FileName; }
      set { _FileName = value; }
    }

    private CmdlinkFileTransfer.GetAudioFile.ConversionType _convert_to = CmdlinkFileTransfer.GetAudioFile.ConversionType.ConvertToLinear16;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"convert_to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CmdlinkFileTransfer.GetAudioFile.ConversionType.ConvertToLinear16)]
    public CmdlinkFileTransfer.GetAudioFile.ConversionType convert_to
    {
      get { return _convert_to; }
      set { _convert_to = value; }
    }

    private bool _enable_agc = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"enable_agc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable_agc
    {
      get { return _enable_agc; }
      set { _enable_agc = value; }
    }

    private int _gain = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gain", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gain
    {
      get { return _gain; }
      set { _gain = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ConversionType")]
    public enum ConversionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConvertToLinear16", Value=0)]
      ConvertToLinear16 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConvertTouLaw", Value=1)]
      ConvertTouLaw = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConvertToaLaw", Value=2)]
      ConvertToaLaw = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConvertToMSADPCM", Value=3)]
      ConvertToMSADPCM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConvertToMp3", Value=4)]
      ConvertToMp3 = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileTransferQuery")]
  public partial class FileTransferQuery : global::ProtoBuf.IExtensible
  {
    public FileTransferQuery() {}
    
    private CmdlinkFileTransfer.FileTransferQuery.CommandType _Command;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CmdlinkFileTransfer.FileTransferQuery.CommandType Command
    {
      get { return _Command; }
      set { _Command = value; }
    }

    private CmdlinkFileTransfer.GetDirectory _getdir = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"getdir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CmdlinkFileTransfer.GetDirectory getdir
    {
      get { return _getdir; }
      set { _getdir = value; }
    }

    private CmdlinkFileTransfer.GetFile _getfile = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"getfile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CmdlinkFileTransfer.GetFile getfile
    {
      get { return _getfile; }
      set { _getfile = value; }
    }

    private CmdlinkFileTransfer.DeleteFile _delfile = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"delfile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CmdlinkFileTransfer.DeleteFile delfile
    {
      get { return _delfile; }
      set { _delfile = value; }
    }

    private CmdlinkFileTransfer.GetAudioFile _getaudiofile = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"getaudiofile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CmdlinkFileTransfer.GetAudioFile getaudiofile
    {
      get { return _getaudiofile; }
      set { _getaudiofile = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CommandType")]
    public enum CommandType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdGetDirectory", Value=0)]
      CmdGetDirectory = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdGetFile", Value=1)]
      CmdGetFile = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdDelFile", Value=2)]
      CmdDelFile = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdGetAudioFile", Value=3)]
      CmdGetAudioFile = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
